---
- name: List to String Conversion
  hosts: localhost
  gather_facts: false
  vars:
    date_start: "2022-11-10"
    time_start: "08:00:00"
    date_end: "2022-11-10"
    time_end: "21:00:00"

    date_time_sample: '2024-10-02 15:49:20'

    current_year_month_string: "{{ lookup('pipe', 'date -d \"8 hours\" +%Y%m') }}"
    current_year_month_date_string: "{{ lookup('pipe', 'date -d \"8 hours\" +%Y%m%d') }}"
    # Get UTC date time to Singapore time
    # date_time_string: "{{ lookup('pipe','date -d \"now + 8 hours\" +%Y-%m-%d_%H-%M-%S') | string }}"
  tasks:

    - name: Print date variables
      ansible.builtin.debug:
        msg:
          - "current_year_month_string: {{ current_year_month_string }}"
          - "current_year_month_date_string: {{ current_year_month_date_string   }}"

    - name: Set variables
      set_fact:
        date_time_epoch_value: "{{ (date_time_sample | to_datetime('%Y-%m-%d %H:%M:%S')).strftime('%s') | int + 60 }}"
        date_time_sample_plus: "{{ lookup('pipe', 'date -d \"{{ date_time_sample }}+0 + 1 hours\" +%Y-%m-%d\\ %H:%M:%S') | string }}"

    - name: Print date time
      ansible.builtin.debug:
        msg:
          # - "{{ date_to_calc }}"
          - "Original UTC: {{ (date_time_sample | to_datetime) }}"

          # +0 at the end means, source is UTC
          - "Original UTC to SGT + 1 hours: {{ lookup('pipe', 'date -d \"{{ date_time_sample }}+0 + 1 hours\" +%Y-%m-%d\\ %H:%M:%S') | string }}"

          - "UTC to SGT + 10 minutes: {{ lookup('pipe', 'date -d \"{{ date_time_sample }}+0 + 10 minutes\" +%Y-%m-%d\\ %H:%M:%S') | string }}"
          - "{{ (date_time_sample_plus | to_datetime('%Y-%m-%d %H:%M:%S')) > (date_time_sample | to_datetime('%Y-%m-%d %H:%M:%S')) }}"
          - "epoch: {{ (date_time_sample | to_datetime('%Y-%m-%d %H:%M:%S')).strftime('%s')  }}"
          - "epoch + 60 min: {{ (date_time_sample | to_datetime('%Y-%m-%d %H:%M:%S')).strftime('%s') | int + 3600 }}"
          # - "epoch + 60 min: {{ (date_time_epoch_value | to_datetime) | strftime('%Y-%m-%d %H:%M:%S') }}"
          - "Cleaned: {{ date_time_sample | replace('-', '') | replace(' ', '') | replace(':', '') }}"
          - "Current time: {{ lookup('pipe','date -d \"now \" +%Y-%m-%d\\ %H:%M:%S') }}"
          - "Current time + 8 hrs: {{ lookup('pipe','date -d \"now + 8 hours\" +%Y-%m-%d\\ %H:%M:%S') }}"
                                                    # (date -d \"2024-10-02 15:49:20 + 8 hours\" +%Y-%m-%d_%H:%M:%S')




    - name: Prepare the date string
      ansible.builtin.set_fact:
        date_start_string: "{{ date_start + ' ' + time_start }}"

    - name: Convert the string to date format
      ansible.builtin.set_fact:
        date_start_string: "{{ date_start_string | to_datetime }}"


        # date_start_string: '{{  date_start + " " + time_start | string | to_datetime("%Y-%m-%d %H:%M:%S") }}'

        #date_end_string: "{{ date_end + ' ' + time_end | to_datetime }}"

# 2022-11-10 08:00:00
# 2016-08-14 20:00:12

    - name: Print the List
      debug:
        msg: "{{ date_start_string }}"

    - name: Time difference
      debug:
        msg: '{{ (("2016-08-14 20:00:12" | to_datetime) - ("2015-12-25" | to_datetime("%Y-%m-%d"))).total_seconds()  }}'



    # - name: Print the List
    #   debug:
    #     msg: "{{ date_start_string }}, {{ date_end_string  }}"

    # - name: Concatenate a list to string
    #   set_fact:
    #     my_string: "{{ my_list | join(',') }}"

    # - name: Print the String
    #   debug:
    #     msg: "{{ my_string }}"

    # - name: "New Task Added"
    #   ansible.builtin.debug:
    #     msg: "This is a new task added for demo"
