# ---
# - name: Converge
#   hosts: all
#   gather_facts: false
#   tasks:
#     - name: Replace this task with one that validates your content
#       ansible.builtin.debug:
#         msg: "This is the effective test"

---
- name: Demo Molecule playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Role Testing
      ansible.builtin.include_role:
        name: iamgini.moleculedemo.demo_role
        tasks_from: main.yml
# ---
# - name: Include a playbook from a collection
#   ansible.builtin.import_playbook: iamgini.moleculedemo.demo

- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
- name: Converge roles
  hosts: molecule
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Print some info
      ansible.builtin.assert:
        that: result.stdout | regex_search("^Linux")

    - name: Include role
      ansible.builtin.include_role:
        name: example.web.install_apache