[windows]
win2019-1 ansible_host=192.168.57.210
win2019-local ansible_host=192.168.57.210

[windows:vars]
# Local User
ansible_user= "Administrator"

#### ====== user's Domain name must be in uppercase============
# ansible_user= "ansible-dns-user@EXAMPLE.COM"

ansible_password= "Welcome123"
ansible_port= "5985"
ansible_connection= "winrm"

# ansible_winrm_transport= "kerberos"
ansible_winrm_transport= "basic"
ansible_winrm_server_cert_validation= ignore
