---
- name: Performing Linux OS Patching
  
  hosts: "{{ NODES }}"
  become: true
  vars:
    email_notificaiton: false
    email_to_address: app-owners@lab.local
    
    ## service list - it can be stored in inventory level as well
    service_list:
      - nginx
      - mysqld
      - httpd
    running_services: ""
    any_service_running: false
  tasks:
    - name: "Pre-Patching: Sending Email to Server and App Owners"
      include_role:
        name: send-email
      vars:
        email_subject: 'OS patching is beginning now'
      when: email_notificaiton
      tags: pretaskemail
    
    - name: "Patching Pre-tasks"
      include_role:
        name: linux-patching
        tasks_from: linux-patching-pre-tasks.yaml
    
    - name: "Patching Tasks"
      include_role:
        name: linux-patching

    - name: "Patching Post-tasks"
      include_role:
        name: linux-patching
        tasks_from: linux-patching-post-tasks.yaml

    - name: "Post-Patching: Sending Email to Server and App Owners"
      include_role:
        name: send-email
      vars:
        email_subject: 'OS patching has been completed'
      when: email_notificaiton
      tags: 
        - posttaskemail
