---
- name: List to String Conversion
  hosts: localhost
  gather_facts: false
  vars:
    my_list:
      - "apple"
      - "mango"
      - "orange"

    mytext: swich1
  tasks:
    - name: Print last char
      ansible.builtin.debug:
        msg: "{{ mytext[-1] }}"

    - name: Print the List
      debug:
        msg: "{{ my_list }}"

    - name: Concatenate a list to string
      set_fact:
        my_string: "{{ my_list | join(',') }}"

    - name: Print the String
      debug:
        msg: "{{ my_string }}"

    - name: "New Task Added"
      ansible.builtin.debug:
        msg: "This is a new task added for demo"

    - name: Print the Job IDs
      debug:
        msg: "Job ID - {{ tower_job_id | default('none') }}, Workflow Job ID - {{ awx_workflow_job_id | default('none') }} "

    # - name: Display all variables/facts known for a host
    #   debug:
    #     var: hostvars[inventory_hostname]
    #   tags: debug_info

    # - name: Print some debug information
    #   vars:
    #     msg: |
    #       Module Variables ("vars"):
    #       --------------------------------
    #       {{ vars | to_nice_json }}

    #       Environment Variables ("environment"):
    #       --------------------------------
    #       {{ environment | to_nice_json }}

    #       GROUP NAMES Variables ("group_names"):
    #       --------------------------------
    #       {{ group_names | to_nice_json }}

    #       GROUPS Variables ("groups"):
    #       --------------------------------
    #       {{ groups | to_nice_json }}

    #       HOST Variables ("hostvars"):
    #       --------------------------------
    #       {{ hostvars | to_nice_json }}

    #   debug:
    #     msg: "{{ msg.split('\n') }}"
    #   tags: debug_info
    # - name: "Pause for testing"
    #   ansible.builtin.pause:
    #     minutes: 5