---
# Local user with HTTPS
ansible_user: "Administrator"
ansible_password: "Welcome123"
ansible_port: "5986"
ansible_connection: "winrm"
ansible_winrm_transport: "ntlm"
ansible_winrm_server_cert_validation: ignore
